services:
  api:
    image: ghcr.io/get-to-the-point/unicat-api:latest
    container_name: unicat-api
    ports:
      - "8081:8080"
    networks:
      - unicat-network
    env_file:
      - .env

  loki:
    image: grafana/loki:3.4.1
    container_name: loki
    ports:
      - "10001:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
    command: -config.file=/etc/loki/loki-config.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "10002:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=unicat.api
      - GF_SECURITY_ADMIN_PASSWORD=unicat.api
      - GF_AUTH_ANONYMOUS_ENABLED=true
    depends_on:
      - loki

  database:
    image: postgres:15-alpine
    container_name: unicat-database
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
        - unicat-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src/main/resources/unicat.day:/etc/nginx/certs:ro
    depends_on:
      - api
    networks:
      - unicat-network

volumes:
  postgres_data:
  grafana-data:

networks:
  unicat-network:
    driver: bridge